vich_uploader:
    db_driver: orm

    mappings:
       lists:
           uri_prefix: /lists/
           upload_destination: '%kernel.project_dir%/public/uploads/lists'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer